In [1]:
import time
import pandas as pd
import numpy as np
import requests
import matplotlib as mp

API

Getting spot data

In [8]:
#spot data

url_spot = "https://api.binance.com/api/v3/klines"

end_time = int(time.time()*1000)

start_time = end_time - (3*365*24*60*60*1000)

params = {
    "symbol" : "BTCUSDT",
    "interval" : "1d",
    "startTime" : start_time,
    "endTime" : end_time,
    "limit" : 1000
}

response = requests.get(url_spot, params=params)

data = response.json()

print(type(data))
print(len(data))
print(data[0])

<class 'list'>
1000
[1683331200000, '29505.60000000', '29820.00000000', '28300.00000000', '28848.20000000', '49249.28459000', 1683417599999, '1429517892.78050220', 1221021, '23315.95073000', '676717267.01172240', '0']

In [12]:
df = pd.DataFrame(data)

df = df.iloc[:,:6]
df.columns = ["timestamp", "open", "high", "low", "close", "volume"]

df["timestamp"] = pd.to_datetime(df["timestamp"], unit="ms")

for col in ["open", "high", "low", "close"]:
    df[col] = df[col].astype(float)

df.head()

   timestamp      open      high       low     close          volume
0 2023-05-06  29505.60  29820.00  28300.00  28848.20  49249.28459000
1 2023-05-07  28848.19  29138.29  28395.23  28430.10  30003.41028000
2 2023-05-08  28430.09  28631.01  27262.00  27668.79  68244.36179000
3 2023-05-09  27668.80  27818.00  27353.00  27628.27  40113.31069000
4 2023-05-10  27628.28  28331.42  26777.00  27598.75  71155.11355000

Getting Futures Data

In [13]:
url_fut = "https://fapi.binance.com/fapi/v1/klines"

response_fut = requests.get(url_fut, params=params)

data_fut = response_fut.json()

print(type(data_fut))
print(data_fut[0])

<class 'list'>
[1683331200000, '29491.50', '29840.00', '28333.00', '28837.80', '475628.901', 1683417599999, '13798897391.83881', 4534010, '230364.328', '6685476928.26591', '0']

In [17]:
df_fut = pd.DataFrame(data_fut) #puts the list into a dataframe

df_fut = df_fut.iloc[:,:6] #selects only the first 6 columns
df_fut.columns = ["timestamp", "open", "high", "low", "close", "volume"] #naming the columns

df_fut["timestamp"] = pd.to_datetime(df_fut["timestamp"], unit="ms") #changes the time from ms to date and ms 

for col in ["open", "high", "low", "close"]:
    df_fut[col] = df_fut[col].astype(float) #changes the numbers from string into float

df_fut.head()

   timestamp     open     high      low    close      volume
0 2023-05-06  29491.5  29840.0  28333.0  28837.8  475628.901
1 2023-05-07  28837.9  29137.0  28370.0  28419.4  308410.643
2 2023-05-08  28419.5  28624.6  27250.0  27659.8  658188.777
3 2023-05-09  27659.8  27815.6  27316.8  27610.2  367664.686
4 2023-05-10  27610.2  28297.0  26666.6  27582.9  722502.676